name: Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - artifact_name: linux-binary
            asset_name: rsmaker
            target: x86_64-unknown-linux-gnu
          - artifact_name: windows-binary
            asset_name: rsmaker.exe
            target: x86_64-pc-windows-gnu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: sudo apt-get install -y mingw-w64

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo +nightly build --release --target ${{ matrix.target }}

      - name: List output files
        run: ls -la target/${{ matrix.target }}/release/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.asset_name }}
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
